# Site settings
title: Introduction to MySQL
email: dangoldin@gmail.com
author: Dan Goldin
description: "Notes for the Coalition 4 Queens Intro to MySQL class"
baseurl: ""
url: "http://dangoldin.com/mysql-class"
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
